# Signif Test for Input Format

qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./gpt-cz-poetry-basic-format-e4e16_LM, IMPROVED=./gpt-cz-poetry-basic-format-e0e4-pretrained_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=BASIC, IMPROVEDINPUT=BASIC'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./Base-Tokenizer-gpt-cz-poetry-verse-param-format-e4e16_LM, IMPROVED=./Base-Tokenizer-gpt-cz-poetry-verse-param-format-e0e4-pretrained_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=VERSE_PAR, IMPROVEDINPUT=VERSE_PAR'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./gpt-cz-poetry-basic-format-e4e16_LM, IMPROVED=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=BASIC, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./Base-Tokenizer-gpt-cz-poetry-verse-param-format-e4e16_LM, IMPROVED=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=VERSE_PAR, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh

# Signif Test for FORCED

qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh

# Signif Test for Tokenizer

qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=FORCED, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=FORCED, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=FORCED, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh

qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=FORCED, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=FORCED, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh

qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, IMPROVED=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=FORCED, IMPROVEDGEN=FORCED, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh

# Signif Test Secondary

qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-base-e4e16_LM, IMPROVED=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-base-e4e16_LM, IMPROVED=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-base-e4e16_LM, IMPROVED=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-base-e4e16_LM, IMPROVED=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-all-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh

# Signif Test Language Learning 

qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-all-e0e24_LM, IMPROVED=./CZ-Base-Tokenizer-NormalText-gpt-cz-poetry-base-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-all-e0e24_LM, IMPROVED=./CZ-New-Processed-BPE-NormalText-gpt-cz-poetry-base-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-all-e0e24_LM, IMPROVED=./CZ-New-Syllable-BPE-NormalText-gpt-cz-poetry-base-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh
qsub -N TestSignif -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-all-e0e24_LM, IMPROVED=./CZ-Unicode-Tokenizer-NormalText-gpt-cz-poetry-base-e4e16_LM, BASEGEN=BASIC, IMPROVEDGEN=BASIC, BASEINPUT=METER_VERSE, IMPROVEDINPUT=METER_VERSE'  shell_scripts/significance_test_helper.sh

### Validators Test ###

# Signif Test Difference RHYME

qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/rhyme/ufal-robeczech-base_BPE_validator_1706753939607, IMPROVED=./utils/validators/rhyme/ufal-robeczech-base_syllable_BPE_validator_1706824640849, BASETOK=ufal/robeczech-base, IMPROVEDTOK=ufal/robeczech-base, BASESYL=false, IMPROVEDSYL=true, TYPE=rhyme, BASECONTEXT=false, IMPROVEDCONTEXT=false'  shell_scripts/significance_test_val_helper.sh
qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/rhyme/distilroberta-base_BPE_validator_1706752010848, IMPROVED=./utils/validators/rhyme/distilroberta-base_syllable_BPE_validator_1706818163442, BASETOK=distilroberta-base, IMPROVEDTOK=distilroberta-base, BASESYL=false, IMPROVEDSYL=true, TYPE=rhyme, BASECONTEXT=false, IMPROVEDCONTEXT=false'  shell_scripts/significance_test_val_helper.sh
qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/rhyme/ufal-robeczech-base_syllable_BPE_validator_1706824640849, IMPROVED=./utils/validators/rhyme/distilroberta-base_syllable_BPE_validator_1706818163442, BASETOK=ufal/robeczech-base, IMPROVEDTOK=distilroberta-base, BASESYL=true, IMPROVEDSYL=true, TYPE=rhyme, BASECONTEXT=false, IMPROVEDCONTEXT=false'  shell_scripts/significance_test_val_helper.sh

# Signif Test Difference METER

qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/meter/distilroberta-base_syllable_BPE_validator_1706946129024, IMPROVED=./utils/validators/meter/Context_distilroberta-base_syllable_BPE_validator_1706818163442, BASETOK=distilroberta-base, IMPROVEDTOK=distilroberta-base, BASESYL=true, IMPROVEDSYL=true, TYPE=meter, BASECONTEXT=false, IMPROVEDCONTEXT=true'  shell_scripts/significance_test_val_helper.sh
qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/meter/distilroberta-base_BPE_validator_1706908625326, IMPROVED=./utils/validators/meter/distilroberta-base_syllable_BPE_validator_1706946129024, BASETOK=distilroberta-base, IMPROVEDTOK=distilroberta-base, BASESYL=false, IMPROVEDSYL=true, TYPE=meter, BASECONTEXT=false, IMPROVEDCONTEXT=false'  shell_scripts/significance_test_val_helper.sh
qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/meter/Context_roberta-base_syllable_BPE_validator_1706876234643, IMPROVED=./utils/validators/meter/Context_distilroberta-base_syllable_BPE_validator_1706818163442, BASETOK=roberta-base, IMPROVEDTOK=distilroberta-base, BASESYL=true, IMPROVEDSYL=true, TYPE=meter, BASECONTEXT=true, IMPROVEDCONTEXT=true'  shell_scripts/significance_test_val_helper.sh

# Signif Test Difference YEAR

qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/year/ufal-robeczech-base_syllable_BPE_validator_1706824640849, IMPROVED=./utils/validators/year/ufal-robeczech-base_BPE_validator_1706753939607, BASETOK=ufal/robeczech-base, IMPROVEDTOK=ufal/robeczech-base, BASESYL=true, IMPROVEDSYL=false, TYPE=year, BASECONTEXT=false, IMPROVEDCONTEXT=false'  shell_scripts/significance_test_val_helper.sh
qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/year/roberta-base_BPE_validator_1706764637259, IMPROVED=./utils/validators/year/ufal-robeczech-base_BPE_validator_1706753939607, BASETOK=roberta-base, IMPROVEDTOK=ufal/robeczech-base, BASESYL=false, IMPROVEDSYL=false, TYPE=year, BASECONTEXT=false, IMPROVEDCONTEXT=false'  shell_scripts/significance_test_val_helper.sh

# Signif Test Weight

qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/rhyme/roberta-base_BPE_validator_1706978482247, IMPROVED=./utils/validators/rhyme/roberta-base_BPE_validator_1706764637259, BASETOK=roberta-base, IMPROVEDTOK=roberta-base, BASESYL=false, IMPROVEDSYL=false, TYPE=rhyme, BASECONTEXT=false, IMPROVEDCONTEXT=false'  shell_scripts/significance_test_val_helper.sh
qsub -N TestSignifVal -q gpu_dgx -l select=1:ncpus=1:ngpus=1:mem=40gb:gpu_mem=12gb:scratch_local=32gb -l walltime=72:00:00 -v 'BASE=./utils/validators/meter/roberta-base_BPE_validator_1706978482247, IMPROVED=./utils/validators/meter/roberta-base_BPE_validator_1706926470572, BASETOK=roberta-base, IMPROVEDTOK=roberta-base, BASESYL=false, IMPROVEDSYL=false, TYPE=meter, BASECONTEXT=false, IMPROVEDCONTEXT=false'  shell_scripts/significance_test_val_helper.sh
